### PR TITLE
tests: Add alignment test

### PR DESCRIPTION
**Pull request by dajohi**

### CODE REVIEW

**Comment by dajohi** [comment]
This test fails on ARM currently

**Comment by dchest** [comment]
Thanks! Do you know how to fix it or should I look into it?

**Comment by dajohi** [comment]
Apparently it works with the arm asm removed, and built with generic.

**Comment by davecgh** [comment]
Also, for another data point, if you modify that test to use `d` instead of `d[1:]` in the call to `Hash` and update `data` to remove the leading `00` (aka make it aligned), the test will pass.

**Comment by dchest** [comment]
OK, thanks. I've verified that it indeed failed the test (on Raspberry Pi 3) and removed ARM assembly until someone sends a PR with a fixed version. (I've created https://github.com/dchest/siphash/tree/arm-asm branch that points to the last commit before removal).

**Comment by rakitzis** [comment]
I'll take a look. Having a repro will definitely help unearth the issue.

**Comment by dchest** [comment]
@rakitzis thank you!

**Comment by davecgh** [comment]
It's here:
```asm
	AND.S	$3,R10,R8
	BNE hashloopunaligned
```

In Go code, that is effectively:

```Go
if val&0x03 != 0 {
	hashloopunaligned()
}
```

**Comment by rakitzis** [comment]
I'm sure the problem is more subtle but I need to sit with the code when I can stop thinking about other things for a little while... it's tricky to get into the right mindset!

**Comment by davecgh** [comment]
To clarify, I didn't mean to imply the root of the issue is there.  I was responding to @Kunde21 about the check that jumps to the check (although for the non 128-bit version).  That definitely is not the root cause of the issue for 32-bit and 64-bit.

**Comment by Kunde21** [comment]
@davecgh That's present in `Hash`, but missing from `Hash128`.

**Comment by rakitzis** [comment]
OK so that might be it, but it's best to sit with the test cases and make sure there is 100% coverage. Unaligned is considerably trickier to get right.

**Comment by rakitzis** [comment]
Answering my own question: it seems armv5 (supported by Go) requires unaligned accesses to be synthesized in software.

**Pull request merged**
